/**
 * End-to-end test harness for the brain + REST surface.
 *
 * Uses the Firestore emulator; requires `firebase emulators:start`
 * to be running on the standard ports (firestore=8080,
 * functions=5001). Run with:
 *
 *   firebase emulators:exec --only firestore,functions \
 *     "npm --workspace=@worktracker/api test"
 *
 * Or, for a self-contained test run with the in-process app:
 *
 *   WORKTRACKER_FIRESTORE_EMULATOR_HOST=localhost:8080 \
 *   FIRESTORE_EMULATOR=true \
 *   npm --workspace=@worktracker/api test
 */

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { getDb } from '../src/firestore.js';

// In the CI runner, the Firestore emulator is already configured
// via FIRESTORE_EMULATOR_HOST; `getDb()` initializes the app
// and applies the production settings (`ignoreUndefinedProperties`)
// before any other Firestore method is called. Tests must use
// the wrapper so settings are applied before the first
// `collection()` / `doc()` / `set()` call freezes them.
const db = getDb();

test('create + transition + reject a version conflict', async () => {
  // 1. Submit a create command.
  const createId = 'cmd-create-' + Date.now();
  await db.collection('commands').doc(createId).set({
    id: createId,
    source: 'test',
    source_event_id: null,
    op: 'create',
    item_id: null,
    payload: {
      kind: 'task',
      title: 'Brain test',
      body: 'hello',
    },
    status: 'queued',
    error: null,
    applied_event_id: null,
    created_at: new Date().toISOString(),
    applied_at: null,
    failure_count: 0,
    failed_at: null,
  });

  // 2. Wait for the brain to apply. The Cloud Function trigger
  //    runs against the emulator; in a local-only test we drive
  //    the brain directly via the exported function.
  //    (For the in-process test, we import the handler.)
  const { handleCommandCreated } = await import('../src/brain.js');
  // Fetch the command doc we just wrote and pass it.
  const snap = await db.collection('commands').doc(createId).get();
  await handleCommandCreated(snap);

  // 3. The command should be `applied` and the work item should
  //    exist.
  const after = await db.collection('commands').doc(createId).get();
  assert.equal(after.data()?.status, 'applied');
  const itemId = (after.data()?.item_id ?? '') as string;
  // `item_id` isn't written on the command itself; the work
  // item id is generated by the create branch. We get it from
  // the events.
  const events = await db
    .collection('work_items')
    .where('source', '==', 'test')
    .where('title', '==', 'Brain test')
    .get();
  assert.equal(events.docs.length, 1);
  const realId = events.docs[0]!.id;
  void itemId;

  // 4. Submit an update with the right version, then submit
  //    an update with a stale version. The second should be
  //    rejected.
  const current = events.docs[0]!.data() as { version: number };
  await db.collection('commands').doc('cmd-update-ok').set({
    id: 'cmd-update-ok',
    source: 'test',
    source_event_id: null,
    op: 'update',
    item_id: realId,
    payload: { patch: { title: 'Brain test (updated)' }, expected_version: current.version },
    status: 'queued',
    error: null,
    applied_event_id: null,
    created_at: new Date().toISOString(),
    applied_at: null,
    failure_count: 0,
    failed_at: null,
  });
  await handleCommandCreated((await db.collection('commands').doc('cmd-update-ok').get()));
  const after2 = await db.collection('commands').doc('cmd-update-ok').get();
  assert.equal(after2.data()?.status, 'applied');

  await db.collection('commands').doc('cmd-update-stale').set({
    id: 'cmd-update-stale',
    source: 'test',
    source_event_id: null,
    op: 'update',
    item_id: realId,
    payload: { patch: { title: 'Brain test (stale)' }, expected_version: 0 },
    status: 'queued',
    error: null,
    applied_event_id: null,
    created_at: new Date().toISOString(),
    applied_at: null,
    failure_count: 0,
    failed_at: null,
  });
  await handleCommandCreated((await db.collection('commands').doc('cmd-update-stale').get()));
  const after3 = await db.collection('commands').doc('cmd-update-stale').get();
  assert.equal(after3.data()?.status, 'rejected');
  assert.match(after3.data()?.error ?? '', /version_conflict/);

  // 5. The conflict should be in the conflicts collection.
  const conflicts = await db
    .collection('conflicts')
    .where('command_id', '==', 'cmd-update-stale')
    .get();
  assert.equal(conflicts.docs.length, 1);
});

test('dead-letter: command with non-existent source after retries → status=failed', async () => {
  // Simulate a command that the brain will repeatedly fail to
  // apply. The brain trigger only runs in Cloud Functions, so we
  // test the dead-letter primitives directly: recordFailure
  // increments failure_count and markFailed flips the status.
  // We assert on the public surfaces (commands/{id}.status and
  // commands/{id}/failures sub-collection).
  const { recordFailure, markFailed } = await import('../src/brain.js');
  const { ulid } = await import('../src/ids.js');
  const cmdId = 'cmd-deadletter-' + Date.now();
  await db.collection('commands').doc(cmdId).set({
    id: cmdId,
    source: 'test',
    source_event_id: null,
    op: 'create',
    item_id: null,
    payload: { kind: 'task', title: 'deadletter' },
    status: 'queued',
    error: null,
    applied_event_id: null,
    created_at: new Date().toISOString(),
    applied_at: null,
    failure_count: 0,
    failed_at: null,
  });
  const cmdRef = db.collection('commands').doc(cmdId);
  // Simulate three recorded failures.
  for (let attempt = 1; attempt <= 3; attempt += 1) {
    await recordFailure(
      db,
      (await cmdRef.get()).data() as any,
      attempt,
      'internal_error',
      `simulated failure #${attempt}`,
      'stack-trace-stub',
    );
  }
  // After three failures, mark as failed.
  await markFailed(db, (await cmdRef.get()).data() as any, 'simulated failure #3');
  const finalDoc = await cmdRef.get();
  const data = finalDoc.data() as any;
  assert.equal(data.status, 'failed');
  assert.equal(data.failure_count, 3);
  assert.ok(data.failed_at, 'failed_at should be set');
  // Failures sub-collection should have 3 entries.
  const failures = await cmdRef.collection('failures').orderBy('attempt', 'asc').get();
  assert.equal(failures.docs.length, 3);
  assert.equal(failures.docs[0].data().attempt, 1);
  assert.equal(failures.docs[2].data().attempt, 3);
  // Cleanup.
  await cmdRef.delete();
});

