/**
 * End-to-end test harness for the brain + REST surface.
 *
 * Uses the Firestore emulator; requires `firebase emulators:start`
 * to be running on the standard ports (firestore=8080,
 * functions=5001). Run with:
 *
 *   firebase emulators:exec --only firestore,functions \
 *     "npm --workspace=@worktracker/api test"
 *
 * Or, for a self-contained test run with the in-process app:
 *
 *   WORKTRACKER_FIRESTORE_EMULATOR_HOST=localhost:8080 \
 *   FIRESTORE_EMULATOR=true \
 *   npm --workspace=@worktracker/api test
 */

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { initializeApp, getApps, applicationDefault } from 'firebase-admin/app';
import { getFirestore } from 'firebase-admin/firestore';

const projectId = 'worktracker-test';

// In the CI runner, the Firestore emulator is already configured
// via FIRESTORE_EMULATOR_HOST; we just need to point the admin
// SDK at the right project.
if (getApps().length === 0) {
  initializeApp({ credential: applicationDefault(), projectId });
}
const db = getFirestore();

test('create + transition + reject a version conflict', async () => {
  // 1. Submit a create command.
  const createId = 'cmd-create-' + Date.now();
  await db.collection('commands').doc(createId).set({
    id: createId,
    source: 'test',
    source_event_id: null,
    op: 'create',
    item_id: null,
    payload: {
      kind: 'task',
      title: 'Brain test',
      body: 'hello',
    },
    status: 'queued',
    error: null,
    applied_event_id: null,
    created_at: new Date().toISOString(),
    applied_at: null,
  });

  // 2. Wait for the brain to apply. The Cloud Function trigger
  //    runs against the emulator; in a local-only test we drive
  //    the brain directly via the exported function.
  //    (For the in-process test, we import the handler.)
  const { handleCommandCreated } = await import('../src/brain.js');
  // Fetch the command doc we just wrote and pass it.
  const snap = await db.collection('commands').doc(createId).get();
  await handleCommandCreated(snap);

  // 3. The command should be `applied` and the work item should
  //    exist.
  const after = await db.collection('commands').doc(createId).get();
  assert.equal(after.data()?.status, 'applied');
  const itemId = (after.data()?.item_id ?? '') as string;
  // `item_id` isn't written on the command itself; the work
  // item id is generated by the create branch. We get it from
  // the events.
  const events = await db
    .collection('work_items')
    .where('source', '==', 'test')
    .where('title', '==', 'Brain test')
    .get();
  assert.equal(events.docs.length, 1);
  const realId = events.docs[0]!.id;
  void itemId;

  // 4. Submit an update with the right version, then submit
  //    an update with a stale version. The second should be
  //    rejected.
  const current = events.docs[0]!.data() as { version: number };
  await db.collection('commands').doc('cmd-update-ok').set({
    id: 'cmd-update-ok',
    source: 'test',
    source_event_id: null,
    op: 'update',
    item_id: realId,
    payload: { patch: { title: 'Brain test (updated)' }, expected_version: current.version },
    status: 'queued',
    error: null,
    applied_event_id: null,
    created_at: new Date().toISOString(),
    applied_at: null,
  });
  await handleCommandCreated((await db.collection('commands').doc('cmd-update-ok').get()));
  const after2 = await db.collection('commands').doc('cmd-update-ok').get();
  assert.equal(after2.data()?.status, 'applied');

  await db.collection('commands').doc('cmd-update-stale').set({
    id: 'cmd-update-stale',
    source: 'test',
    source_event_id: null,
    op: 'update',
    item_id: realId,
    payload: { patch: { title: 'Brain test (stale)' }, expected_version: 0 },
    status: 'queued',
    error: null,
    applied_event_id: null,
    created_at: new Date().toISOString(),
    applied_at: null,
  });
  await handleCommandCreated((await db.collection('commands').doc('cmd-update-stale').get()));
  const after3 = await db.collection('commands').doc('cmd-update-stale').get();
  assert.equal(after3.data()?.status, 'rejected');
  assert.match(after3.data()?.error ?? '', /version_conflict/);

  // 5. The conflict should be in the conflicts collection.
  const conflicts = await db
    .collection('conflicts')
    .where('command_id', '==', 'cmd-update-stale')
    .get();
  assert.equal(conflicts.docs.length, 1);
});
